"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowRight, LockKeyhole, ShieldCheck } from "lucide-react";
export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push(data.redirect); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível entrar."); } finally { setBusy(false); } }
  return <main className="login-shell"><div className="login-brand"><Image src="/brand/focus-logo-horizontal-white.png" alt="Focus Solutions" width={190} height={72} priority /><div className="login-brand-copy"><span className="login-emblem"><ShieldCheck size={25} /></span><p>CONFIANÇA COMEÇA COM ESCUTA</p><h2>Integridade se constrói com transparência e cuidado.</h2><span>Uma gestão ética começa por criar espaço para que as pessoas possam falar.</span></div><small className="login-brand-foot">FOCUS SOLUTIONS <i /> CANAL DE ÉTICA</small></div><section className="login-side"><div className="login-form-wrap"><div className="login-mobile-logo"><Image src="/brand/focus-logo-horizontal.png" alt="Focus Solutions" width={170} height={65} /></div><p className="eyebrow">ÁREA RESTRITA</p><h1>Bem-vindo de volta</h1><p className="login-sub">Entre na sua conta para acessar o Canal de Ética.</p><form onSubmit={submit}><label>E-mail corporativo<input type="email" autoComplete="username" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nome@empresa.com.br" /></label><label>Senha<input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Sua senha" /></label><button className="login-submit" disabled={busy}>{busy ? "Entrando…" : "Entrar"}<ArrowRight size={17} /></button>{error && <p className="login-error">{error}</p>}</form><div className="login-safe"><LockKeyhole size={14} /> Conexão segura e criptografada</div></div><footer>Focus Solutions <span>·</span> Canal de Ética</footer></section></main>;
}
