"use client";
import { useEffect, useState } from "react";
import { Plus, ToggleLeft, ToggleRight } from "lucide-react";
type Overview={users:{id:string;name:string;email:string;role:string;active:boolean;company:string}[];categories:{id:string;name:string;description:string|null;active:boolean}[];companies:{id:string;name:string;slug:string;active:boolean;createdAt:string;users:number;complaints:number}[]};
export function AdminTools({section}:{section:string}){
 const[data,setData]=useState<Overview|null>(null);const[name,setName]=useState("");const[description,setDescription]=useState("");const[error,setError]=useState("");
 const refresh=()=>fetch("/api/admin/overview").then(r=>r.ok?r.json():null).then(setData).catch(()=>setData(null));useEffect(()=>{refresh();},[]);
 async function add(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/overview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,description})});const body=await r.json();if(!r.ok){setError(body.error);return;}setName("");setDescription("");refresh();}
 async function toggle(id:string,active:boolean){const r=await fetch("/api/admin/overview",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active:!active})});if(!r.ok){const body=await r.json();setError(body.error);return;}refresh();}
 if(!data)return <section className="panel admin-empty"><span>…</span><h2>Carregando dados da plataforma</h2><p>A área aparece depois que o banco de dados estiver disponível.</p></section>;
 if(section==="usuarios")return <section className="panel listing-panel"><div className="admin-tools-heading"><div><h2>Usuários da plataforma</h2><p>Contas Focus e usuários associados às empresas clientes.</p></div><span>{data.users.length} usuários</span></div><div className="table-wrap"><table><thead><tr><th>USUÁRIO</th><th>E-MAIL</th><th>EMPRESA</th><th>PERFIL</th><th>STATUS</th></tr></thead><tbody>{data.users.map(user=><tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.company}</td><td>{user.role.replaceAll("_"," ")}</td><td><span className={`company-status ${user.active?"":"inactive"}`}><i/>{user.active?"Ativo":"Inativo"}</span></td></tr>)}</tbody></table></div></section>;
 if(section==="uso")return <><section className="admin-stat-grid">{[["Empresas",data.companies.length],["Usuários",data.users.length],["Denúncias",data.companies.reduce((n,c)=>n+c.complaints,0)]].map(([label,value])=><div className="admin-stat" key={String(label)}><small>{String(label)}</small><b>{value}</b><em>total da plataforma</em></div>)}</section><section className="panel listing-panel"><div className="admin-tools-heading"><div><h2>Uso por empresa</h2><p>Volume agregado de contas e relatos por tenant.</p></div></div><div className="table-wrap"><table><thead><tr><th>EMPRESA</th><th>SLUG</th><th>USUÁRIOS</th><th>DENÚNCIAS</th><th>STATUS</th></tr></thead><tbody>{data.companies.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.slug}</td><td>{c.users}</td><td>{c.complaints}</td><td>{c.active?"Ativa":"Inativa"}</td></tr>)}</tbody></table></div></section></>;
 return <><section className="panel listing-panel"><div className="admin-tools-heading"><div><h2>Categorias globais</h2><p>Opções disponíveis nos canais públicos dos clientes.</p></div></div><div className="settings-item-list">{data.categories.map(item=><div className="settings-item" key={item.id}><span className="settings-item-icon">◆</span><div><b>{item.name}</b><small>{item.description||"Categoria administrada pela Focus Solutions"}</small></div><button className={`switch-button ${item.active?"on":""}`} onClick={()=>toggle(item.id,item.active)}>{item.active?<ToggleRight/>:<ToggleLeft/>}<span>{item.active?"Ativa":"Inativa"}</span></button></div>)}{!data.categories.length&&<p className="settings-empty">Nenhuma categoria global cadastrada.</p>}</div><form className="settings-add" onSubmit={add}><b>Adicionar categoria global</b><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da categoria"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição opcional"/><button className="button button-primary"><Plus size={14}/> Adicionar</button>{error&&<small className="settings-notice">{error}</small>}</form></section></>;
}
