"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, FileText, LockKeyhole, MapPin, ShieldCheck, Upload, X } from "lucide-react";

const categories = ["Assédio moral", "Assédio sexual", "Discriminação", "Fraude", "Corrupção", "Conflito de interesses", "Agressão ou ameaça", "Violação de normas internas", "Segurança do trabalho", "Comportamento inadequado", "Outro", "Não sei classificar"];
const units = ["Matriz", "Rio de Janeiro", "Macaé", "Santos", "Vitória"];
const departments = ["Administrativo", "Financeiro", "Operações", "Recursos Humanos", "Comercial", "Tecnologia", "Logística", "Jurídico"];
const steps = ["Sobre o ocorrido", "Detalhes", "Relato", "Evidências", "Revisão"];
type Form = { category: string; unit: string; department: string; occurredPeriod: string; recurring: string; still: string; description: string; goodFaith: boolean };
const initial: Form = { category: "", unit: "", department: "", occurredPeriod: "", recurring: "", still: "", description: "", goodFaith: false };
const periods = [["TODAY", "Hoje"], ["LAST_7_DAYS", "Nos últimos 7 dias"], ["LAST_30_DAYS", "Nos últimos 30 dias"], ["OVER_30_DAYS", "Há mais de 30 dias"], ["UNKNOWN", "Não sei informar"]];

export function PublicPortal({ slug }: { slug: string }) {
  const [companyName, setCompanyName] = useState(slug.replaceAll("-", " "));
  const [companyUnits, setCompanyUnits] = useState(units);
  const [companyDepartments, setCompanyDepartments] = useState(departments);
  const [companyCategories, setCompanyCategories] = useState(categories);
  const [channelError, setChannelError] = useState(false);
  const [step, setStep] = useState(-1);
  const [form, setForm] = useState(initial);
  const [file, setFile] = useState<File | null>(null);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/public/channel/${encodeURIComponent(slug)}`).then(async response => { if (!response.ok) throw new Error("Canal indisponível"); return response.json(); }).then(data => { setCompanyName(data.name); if (data.units.length) setCompanyUnits(data.units); if (data.departments.length) setCompanyDepartments(data.departments); if (data.categories.length) setCompanyCategories(data.categories); }).catch(() => setChannelError(true)); }, [slug]);
  const change = (key: keyof Form, value: string | boolean) => setForm((f) => ({ ...f, [key]: value }));
  const canContinue = step === 0 ? !!form.category : step === 1 ? !!form.occurredPeriod && !!form.recurring && !!form.still : step === 2 ? form.description.trim().length >= 20 : true;
  const submit = async () => {
    setBusy(true); setError("");
    try {
      const payload = { companySlug: slug, category: form.category, unit: form.unit && form.unit !== "Prefiro não informar" ? form.unit : undefined, department: form.department && !["Não sei", "Prefiro não informar"].includes(form.department) ? form.department : undefined, occurredPeriod: form.occurredPeriod, isRecurring: form.recurring === "Sim" ? true : form.recurring === "Não" ? false : null, isStillOccurring: form.still === "Sim" ? true : form.still === "Não" ? false : null, description: form.description, goodFaith: form.goodFaith };
      const body = new FormData(); body.set("complaint", JSON.stringify(payload)); if (file) body.set("file", file);
      const response = await fetch("/api/public/complaints", { method: "POST", body });
      if (!response.ok) { const data = await response.json(); throw new Error(data.error || "Não foi possível registrar agora."); }
      setSent(true);
    } catch (e) { setError(e instanceof Error ? e.message : "Erro inesperado."); }
    finally { setBusy(false); }
  };
  const option = (value: string, selected: string, key: keyof Form) => <button type="button" className={`choice ${selected === value ? "selected" : ""}`} onClick={() => change(key, value)}>{value}{selected === value && <Check size={17} />}</button>;
  if (channelError) return <main className="public-shell"><header className="public-header"><Image src="/brand/focus-logo-horizontal.png" alt="Focus Solutions" width={200} height={75} /></header><section className="success-box"><p className="eyebrow">CANAL DE ÉTICA</p><h1>Este canal não está disponível.</h1><p>Confira o endereço ou entre em contato com a empresa.</p></section></main>;
  if (sent) return <main className="public-shell"><header className="public-header"><Image src="/brand/focus-logo-horizontal.png" alt="Focus Solutions" width={200} height={75} priority /></header><section className="success-box"><span className="success-icon"><Check size={25} /></span><p className="eyebrow">CANAL DE ÉTICA</p><h1>Denúncia registrada com sucesso.</h1><p>Obrigado por utilizar o Canal de Ética.</p><p className="muted">Seu relato foi recebido com confidencialidade. Não é necessário acompanhar ou consultar um protocolo.</p><button className="button button-primary" onClick={()=>{setSent(false);setForm(initial);setFile(null);setStep(-1);setError("");}}>Registrar outra denúncia</button></section></main>;
  if (step < 0) return <main className="public-shell"><header className="public-header"><Image src="/brand/focus-logo-horizontal.png" alt="Focus Solutions" width={200} height={75} priority /><div className="secure-label"><LockKeyhole size={14} /> AMBIENTE SEGURO</div></header><section className="public-hero"><div className="hero-copy"><p className="eyebrow">CANAL DE ÉTICA</p><h1>Um espaço seguro<br />para fazer o que é certo.</h1><p>Este é um ambiente seguro para relatar situações que violem princípios éticos, normas internas ou a legislação.</p><p>Você não precisa se identificar. Conte o que aconteceu no seu tempo e do seu jeito.</p><div className="privacy-callout"><ShieldCheck size={22} /><span><strong>Sua denúncia é anônima</strong><small>Não solicitamos dados pessoais para registrar um relato.</small></span></div><button className="button button-primary start-button" onClick={() => setStep(0)}>Realizar denúncia <ArrowRight size={18} /></button><p className="emergency-note">Este canal não deve ser usado para situações de emergência.</p></div><aside className="hero-aside"><span className="shield-art"><ShieldCheck size={42} /></span><strong>Confidencialidade em primeiro lugar</strong><p>Compartilhe apenas o que se sentir confortável em relatar. O importante é compreendermos os fatos.</p><div className="aside-rule" /><span className="company-name">Canal da empresa <b>{companyName}</b></span></aside></section><footer className="public-footer"><Image src="/brand/focus-symbol.png" alt="" width={23} height={23} /><span>Canal de Ética disponibilizado por <strong>Focus Solutions</strong></span><span className="footer-lock"><LockKeyhole size={13} /> Conexão protegida</span></footer></main>;
  return <main className="public-shell"><header className="public-header"><Image src="/brand/focus-logo-horizontal.png" alt="Focus Solutions" width={174} height={65} /><div className="secure-label"><LockKeyhole size={14} /> DENÚNCIA ANÔNIMA</div></header><section className="wizard-wrap"><div className="wizard-top"><button className="back-link" onClick={() => step === 0 ? setStep(-1) : setStep(step - 1)}><ArrowLeft size={16} /> Voltar</button><span className="step-counter">{step + 1} <span>de</span> 5</span></div><div className="progress-track"><span style={{ width: `${((step + 1) / 5) * 100}%` }} /></div><div className="step-labels">{steps.map((s, i) => <span className={i === step ? "active" : i < step ? "done" : ""} key={s}>{s}</span>)}</div>
    <div className="wizard-card"><p className="eyebrow">ETAPA {step + 1} DE 5</p>
    {step === 0 && <><h1>Qual situação melhor representa o ocorrido?</h1><p className="muted">Escolha a opção que mais se aproxima. Você poderá dar detalhes depois.</p><div className="category-grid">{companyCategories.map((item, i) => <button type="button" key={item} className={`category-option ${form.category === item ? "selected" : ""}`} onClick={() => change("category", item)}><span className="category-icon">{item.toLowerCase().includes("não sei") ? <CircleHelp /> : item === "Outro" ? <FileText /> : <ShieldCheck />}</span><span>{item}</span>{form.category === item && <Check className="category-check" size={17} />}</button>)}</div></>}
    {step === 1 && <><h1>Ajude a contextualizar a situação.</h1><p className="muted">Responda apenas o que souber. Não é necessário informar uma data exata.</p><div className="field-block"><label><MapPin size={16} /> Onde aconteceu?</label><div className="choice-grid">{[...companyUnits, "Prefiro não informar"].map((u) => option(u, form.unit, "unit"))}</div></div><div className="field-block"><label>Em qual setor ocorreu?</label><select value={form.department} onChange={(e) => change("department", e.target.value)}><option value="">Selecione uma opção</option>{companyDepartments.map((d) => <option key={d}>{d}</option>)}<option>Não sei</option><option>Prefiro não informar</option></select></div><div className="field-block"><label>Quando aconteceu?</label><div className="choice-grid">{periods.map(([v, t]) => <button type="button" className={`choice ${form.occurredPeriod === v ? "selected" : ""}`} onClick={() => change("occurredPeriod", v)} key={v}>{t}{form.occurredPeriod === v && <Check size={17} />}</button>)}</div></div><div className="field-row"><div className="field-block"><label>Aconteceu mais de uma vez?</label><div className="choice-grid compact">{["Sim", "Não", "Não sei"].map((v) => option(v, form.recurring, "recurring"))}</div></div><div className="field-block"><label>A situação continua acontecendo?</label><div className="choice-grid compact">{["Sim", "Não", "Não sei"].map((v) => option(v, form.still, "still"))}</div></div></div></>}
    {step === 2 && <><h1>Conte o que aconteceu.</h1><p className="muted">Descreva a situação com suas próprias palavras. Inclua detalhes que ajudem a compreender os fatos, mas evite informar seus dados pessoais caso queira permanecer anônimo.</p><label className="input-label" htmlFor="description">Relato <span>Obrigatório</span></label><textarea id="description" className="description-input" maxLength={12000} value={form.description} onChange={(e) => change("description", e.target.value)} placeholder="O que aconteceu? Onde? Quando? Quem estava presente? Escreva apenas o que souber."/><div className="textarea-meta"><span>Mínimo de 20 caracteres</span><span>{form.description.length} / 12.000</span></div><div className="note-callout"><ShieldCheck size={17} /> Não tente identificar ou incluir seus dados pessoais se preferir manter o anonimato.</div></>}
    {step === 3 && <><h1>Você possui algum arquivo que possa ajudar?</h1><p className="muted">O envio é opcional. Não é necessário enviar qualquer arquivo para concluir sua denúncia.</p><label className="upload-zone"><input type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><Upload size={25} /><strong>{file ? file.name : "Selecionar arquivo"}</strong><span>PDF, JPG, JPEG, PNG, DOC ou DOCX · até 10 MB</span></label>{file && <button className="remove-file" onClick={() => setFile(null)}><X size={14} /> Remover arquivo</button>}<div className="note-callout"><LockKeyhole size={16} /> Os arquivos enviados são tratados como evidências confidenciais.</div></>}
    {step === 4 && <><h1>Revise seu relato.</h1><p className="muted">Confira as informações antes de enviar. Você ainda pode voltar e editar qualquer etapa.</p><div className="review-list">{[["Sobre o ocorrido", form.category, 0], ["Local e detalhes", `${form.unit || "Unidade não informada"} · ${form.department || "Setor não informado"} · ${periods.find(([v]) => v === form.occurredPeriod)?.[1] || "Período não informado"}`, 1], ["Relato", form.description, 2], ["Evidências", file?.name || "Nenhum arquivo anexado", 3]].map(([title, value, target]) => <div className="review-row" key={String(title)}><div><small>{title}</small><p>{String(value)}</p></div><button onClick={() => setStep(Number(target))}>Editar <ChevronRight size={14} /></button></div>)}</div><label className="consent"><input type="checkbox" checked={form.goodFaith} onChange={(e) => change("goodFaith", e.target.checked)} /><span>Confirmo que as informações foram fornecidas de boa-fé e correspondem ao meu conhecimento sobre os fatos.</span></label>{error && <p className="form-error">{error}</p>}</>}
    {step < 4 ? <button className="button button-primary wizard-next" disabled={!canContinue} onClick={() => setStep(step + 1)}>Continuar <ArrowRight size={17} /></button> : <button className="button button-primary wizard-next" disabled={!form.goodFaith || busy} onClick={submit}>{busy ? "Enviando…" : "Enviar denúncia"} {!busy && <ArrowRight size={17} />}</button>}
    </div><p className="wizard-foot"><LockKeyhole size={13} /> Suas respostas são confidenciais e não incluem dados de identificação.</p></section></main>;
}
