"use client";
import { useEffect, useState } from "react";
import { Download, LockKeyhole } from "lucide-react";
type Report = { total: number; inAnalysis: number; closed: number; averageDays: number | null; privacyHidden: boolean; categories: { name: string; count: number }[]; units: { name: string; count: number }[]; departments: { name: string; count: number }[]; severity: { name: string; count: number }[]; result: { name: string; count: number }[]; recurring: { name: string; count: number }[]; withEvidence: number; withoutEvidence: number };
export function ReportsWorkspace() {
 const [period,setPeriod]=useState("Últimos 12 meses"); const [unit,setUnit]=useState("Todas as unidades"); const [department,setDepartment]=useState("Todos os setores"); const [category,setCategory]=useState("Todas as categorias"); const [data,setData]=useState<Report|null>(null);
 useEffect(()=>{const q=new URLSearchParams({period,unit,department,category});fetch(`/api/client/dashboard?${q}`).then(r=>r.ok?r.json():null).then(setData).catch(()=>setData(null));},[period,unit,department,category]);
 function exportCsv(){if(!data)return;const rows=[["Indicador","Valor"],["Denúncias recebidas",String(data.total)],["Em análise",String(data.inAnalysis)],["Encerradas",String(data.closed)],["Tempo médio (dias)",String(data.averageDays??"")],...[...data.categories.map(x=>[`Categoria: ${x.name}`,String(x.count)]),...data.units.map(x=>[`Unidade: ${x.name}`,String(x.count)]),...data.departments.map(x=>[`Setor: ${x.name}`,String(x.count)]),...data.severity.map(x=>[`Criticidade: ${x.name}`,String(x.count)]),...data.result.map(x=>[`Resultado: ${x.name}`,String(x.count)])]];const csv="\uFEFF"+rows.map(row=>row.map(x=>`"${x.replaceAll('"','""')}"`).join(";")).join("\r\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download="relatorio-canal-etica.csv";link.click();URL.revokeObjectURL(link.href);}
 return <><section className="filter-panel report-filters"><div className="filter-heading"><div><span>Escopo do relatório</span></div></div><div className="filter-controls"><label><span>Período</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Últimos 12 meses</option><option>Últimos 30 dias</option><option>Últimos 90 dias</option><option>Este ano</option></select></label><label><span>Unidade</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option>Todas as unidades</option>{["Matriz","Rio de Janeiro","Macaé","Santos","Vitória"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Setor</span><select value={department} onChange={e=>setDepartment(e.target.value)}><option>Todos os setores</option>{["Administrativo","Financeiro","Operações","Recursos Humanos","Comercial","Tecnologia","Logística","Jurídico"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>Todas as categorias</option>{["Assédio moral","Assédio sexual","Discriminação","Fraude","Corrupção","Conflito de interesses","Agressão ou ameaça","Violação de normas internas","Segurança do trabalho","Comportamento inadequado","Outro","Não sei classificar"].map(x=><option key={x}>{x}</option>)}</select></label></div></section><div className="report-heading"><div><h2>Visão executiva</h2><p>Resumo consolidado para o período e os filtros selecionados.</p></div><button className="button button-quiet" onClick={exportCsv} disabled={!data}><Download size={15}/> Baixar CSV</button></div><section className="stat-grid"><ReportMetric title="Denúncias recebidas" value={data?.total}/><ReportMetric title="Em análise" value={data?.inAnalysis}/><ReportMetric title="Encerradas" value={data?.closed}/><ReportMetric title="Tempo médio de tratamento" value={data?.averageDays==null?"—":`${data.averageDays} dias`}/></section>{data?.privacyHidden&&<div className="privacy-box"><LockKeyhole size={14}/>{"Dados ocultados para preservar a confidencialidade dos relatos."}</div>}{data?.total===0&&<div className="report-empty">Nenhuma denúncia encontrada para o período e filtros selecionados.</div>}<div className="report-grid">{[["Principais categorias",data?.categories],["Distribuição por unidade",data?.units],["Distribuição por setor",data?.departments],["Criticidade interna",data?.severity],["Resultado das análises",data?.result],["Recorrência",data?.recurring]].map(([title,rows])=><article className="panel report-card" key={String(title)}><h3>{String(title)}</h3>{data?.privacyHidden?<small className="muted">Dados ocultados para preservar a confidencialidade.</small>:<ul>{(rows as {name:string;count:number}[]|undefined)?.map(item=><li key={item.name}><span>{item.name}</span><b>{item.count}</b></li>)}</ul>}</article>)}</div><div className="report-footnote">Relatório agregado · o texto dos relatos e observações internas não é incluído no arquivo.</div></>;
}
function ReportMetric({title,value}:{title:string;value:number|string|undefined}){return <article className="stat-card report-metric"><span className="stat-label">{title}</span><div className="stat-value">{value??"—"}</div><span className="stat-note">indicador do período</span></article>;}
